### ISSUE TITLE
Non standard pms paths don't work

### ISSUE THREAD

**Issue by vanstinator** [vanstinator/core-manager#11]

**Comment by briancwelch** [comment]
![image](https://user-images.githubusercontent.com/3002855/106091768-ec1a8080-60e1-11eb-9528-8664e0f1088b.png)
Not sure if related, but core manager won't find my PMS installation, though I hadn't thought I put it in a non-standard directory.

**Comment by vanstinator** [comment]
Possible related. The directory we're looking for us under `%USERPROFILE%\AppData\Local\Plex Media Server`

**Comment by briancwelch** [comment]
Ah ok.  Yeah, that directory doesn't reside on my installation because my Plex library is quite huge (over 5,000 movies and 40,000 episodes of TV shows) and the library itself has had a lot of customization hours put into it, so it's all kept on a separate internal drive (non-networked); in my specific instance this would be E:\Plex Media Server.  While I am just a PHP dev and can't really offer a pull request, I can offer my 2 cents of adding in a config option that allows the user to select their location should the default one not be found.   Thanks for all your hard work.

**Comment by vanstinator** [comment]
This work is in progress https://github.com/vanstinator/core-manager/tree/feature/user-prefs
